library(WGCNA)
library(NetComp)
library(doMC)
library(foreach)
#registerDoMC(cores = 16)
registerDoMC(cores = 4)
msmm_rnaseq=msmm_rnaseq.corr.threshold=list()
msmm_rnaseq.corr.threshold[[1]]=msmm_rnaseq.corr.threshold[[2]]=msmm_rnaseq.corr.threshold[[3]]=list()
#setwd("/shared/hidelab2/user/md4zsa/Work/Data/MSMM_RNAseq/")
setwd("/Users/sandeepamberkar/Work/Data/MSMM-MSBB-HBTRC-Data/MSMM_RNAseq/")
msmm_rnaseq[[1]]=read.table("MSMM_RNAseq_FP_B1_5k.tsv",sep="\t",header=T,as.is=T,row.names=1)
msmm_rnaseq[[2]]=read.table("MSMM_RNAseq_PHG_B1_5k.tsv",sep="\t",header=T,as.is=T,row.names=1)
msmm_rnaseq[[3]]=read.table("MSMM_RNAseq_STG_B1_5k.tsv",sep="\t",header=T,as.is=T,row.names=1)
msmm_rnaseq=lapply(msmm_rnaseq,t)
msmm_rnaseq.corr=lapply(msmm_rnaseq,corFast)
msmm_rnaseq.corr=lapply(msmm_rnaseq.corr,abs)
corr.threshold=c(0.5,0.9)
for (m in 2:3)
  msmm_rnaseq.corr.threshold[[m]] <- foreach(i=corr.threshold) %dopar% matrix_threshold(as.matrix(msmm_rnaseq.corr[[m]]),threshold=i,abs = T)
save.image(file="msmm_rnaseq_corr.RData")